version: '3'
services:
  app:
    container_name: esportal-scraper
    restart: always
    build: .
    ports:
      - 3555:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 2717:27017
