version: '3'
services:
  app:
    container_name: esportal-scraper
    restart: unless-stopped
    build: .
    ports:
      - 3555:3000
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/esportal-scraper
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    # ports:
    #   - 2717:27017
    volumes:
      - mongodb-test:/data/db
volumes:
  mongodb-test:
