version: '3'
services:
  app:
    container_name: esportal-scraper
    restart: always
    build: .
    ports:
      - 3555:3000
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - 2717:27017
    volumes:
      - mongodb-test:/data/db
volumes:
  mongodb-test:
